version: 2

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true

build:
  os: ubuntu-20.04
  tools:
    python: "3.9"

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
