#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# documentation build configuration file, created by
# sphinx-quickstart on Tue Jun 13 22:58:12 2017.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# -- Project information -----------------------------------------------------
import importlib.metadata

metadata = importlib.metadata.metadata("snug")

project = metadata["Name"]
author = metadata["Author"]
version = metadata["Version"]
release = metadata["Version"]


# -- General configuration ------------------------------------------------

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.intersphinx",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
]
templates_path = ["_templates"]
source_suffix = ".rst"

master_doc = "index"
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

# -- Options for HTML output ----------------------------------------------

autodoc_member_order = "bysource"
html_theme = "furo"
highlight_language = "python3"
intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
    "gentools": ("http://gentools.readthedocs.org/en/latest/", None),
    "aiohttp": ("http://aiohttp.readthedocs.org/en/latest/", None),
    "requests": ("http://requests.readthedocs.org/en/latest/", None),
}
